### ISSUE TITLE
when will the benchmark be made available?

### ISSUE THREAD

**Issue by jiahao68** [KangLiao929/Awesome-Deep-Camera-Calibration#1]
when will the benchmark be made available?

**Comment by KangLiao929** [comment]
> when will the benchmark be made available?



> when will the benchmark be made available?

Hi, thanks for your interest. The benchmark will be made available in 2-3 weeks.

**Comment by KangLiao929** [comment]
> when will the benchmark be made available?

Hi, thanks for your interest. The benchmark will be made available in 2-3 weeks.

**Comment by nicoduchene** [comment]
Hello, any news on the benchmark?

**Comment by bhack** [comment]
Gently ping.

**Comment by KangLiao929** [comment]
> Gently ping.

Thanks guys. We promise the benchmark will be released before the publication of our survey paper (expected in 1-2 months).

**Comment by KangLiao929** [comment]
> Hello, any news on the benchmark?

Hi guys, the benchmark has been released. Welcome to use!
