### ISSUE TITLE
clerical error

### ISSUE THREAD

**Issue by ESRSchao** [KangLiao929/Awesome-Deep-Camera-Calibration#2]
I noticed a minor discrepancy in your project and paper regarding the network name used in the description of the paper 'Keypoint-Based LiDAR-Camera Online Calibration With Robust Geometric Network' published in 2020. The original paper refers to the network as RGKCNet, but in your references, it is mentioned as RKGCNet, which is inconsistent with the original text. Thank you very much for the excellent summary work you have done, and I hope correcting this small flaw will make your project even more perfect! 🙌

**Comment by KangLiao929** [comment]
> I noticed a minor discrepancy in your project and paper regarding the network name used in the description of the paper 'Keypoint-Based LiDAR-Camera Online Calibration With Robust Geometric Network' published in 2020. The original paper refers to the network as RGKCNet, but in your references, it is mentioned as RKGCNet, which is inconsistent with the original text. Thank you very much for the excellent summary work you have done, and I hope correcting this small flaw will make your project even more perfect! 🙌

Hi,
Thanks for your interest and we are very grateful for your pointed issues.
Best
